resolver: nightly-2018-12-27

extra-deps:
  - cabal-plan-0.5.0.0
  - git: https://github.com/beauvankirk/cabal-helper.git
    commit: 2f73854e53977ab441310bf577028af099610b9b
packages:
  - .
  - ./core
