# resolver: nightly-2018-06-29
resolver: snapshot.yaml

packages:
- .
- 'core'

extra-deps:
# - ./submodules/ghc-mod/core
# - ./submodules/monad-journal

# - syz-0.2.0.0
# - ghc-exactprint-0.5.7.1
# - pretty-show-1.8.1
# - cabal-helper-0.8.1.2
# - cabal-helper-0.8.1.0@rev:0


# - cabal-plan-0.3.0.0
# - temporary-1.2.1.1
# - base-compat-0.9.3
# Neded for the tests
# - conversion-1.2.1
# - conversion-case-insensitive-1.0.0.0
# - conversion-text-1.0.1
# - conversion-bytestring-1.0.1

#----------------------------------------------------
